app/models/offer.rb, db/migrate/20220523103231_create_offers.rb, test/models/offer_test.rb
=> Created Offer Model

Gemfile.lock, app/models/reservation.rb, db/migrate/20220523104341_create_reservations.rb, db/schema.rb, test/models/reservation_test.rb
=> reservation model created

app/controllers/offers_controller.rb, app/controllers/reservations_controller.rb, config/routes.rb, test/controllers/offers_controller_test.rb, test/controllers/reservations_controller_test.rb
=> routes and controller created

app/controllers/application_controller.rb
Added first_name and last_name to devise
=> added first and last name to devise

app/controllers/offers_controller.rb, app/views/offers/index.html.erb
Offer's index done with links to reservations new & offer's show
=> Offers index with links done

app/controllers/offers_controller.rb, app/views/offers/show.html.erb
if its a users own offer, he can edit or delete, if not - he can reserve it
=> Added buttons on offer#show

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb
=> pundit install

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_form.scss, app/views/offers/_form.html.erb, app/views/offers/show.html.erb
Added _form scss component, and some containers in show, edit and new
=> added some css style for new, edit and show offer

app/controllers/pages_controller.rb, app/controllers/reservations_controller.rb, app/policies/reservation_policy.rb, app/views/reservations/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/seeds.rb, test/policies/reservation_policy_test.rb
pundit reservations
seed update
skipped authentication for homepage
=> Pundit reservations

app/views/offers/show.html.erb
all photos displayed on the top, if there aren't any, display nothing
=> added if photos, display, if not - its ok

app/controllers/pages_controller.rb, app/views/offers/show.html.erb
=> changed space between name and last name

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/views/offers/show.html.erb
=> Finished buttons component

app/views/offers/show.html.erb
map wasn't showing in offer#show
=> still working on the map

app/controllers/offers_controller.rb, app/models/offer.rb, app/views/offers/_form.html.erb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, db/migrate/20220523103231_create_offers.rb, db/schema.rb, db/seeds.rb
changed localisation to location
=> changed localisaton to location

app/controllers/application_controller.rb
=> fixed hobbit boolean input

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb
=> Footer fixed

app/controllers/reviews_controller.rb, app/models/review.rb, app/models/user.rb, db/migrate/20220526090856_create_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
=> Created review model and reviews controller

app/controllers/profiles_controller.rb, app/models/user.rb, app/policies/profile_policy.rb, app/views/profiles/profile.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/controllers/profiles_controller_test.rb, test/controllers/users_controller_test.rb, test/policies/profile_policy_test.rb, test/policies/user_policy_test.rb
added Profile page and Profile controller with respective policies
=> added Profile controller and profile.html.erb

app/controllers/application_controller.rb, app/controllers/profiles_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/profiles/profile.html.erb, config/routes.rb
/profile -- can see my profile with picture, info, reviews and button to edit it
=> Upload profile pic

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
Look at the new amazing footer
=> Footer reworked (added icons with github links)

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
=> Alert on homepage fixed

.rubocop.yml, app/models/reservation.rb, app/policies/reservation_policy.rb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, app/views/reservations/_reservation.html.erb, app/views/reviews/_form.html.erb, db/seeds/common.rb
-Reservations are ordered by created_at so they don't look like they are jumping around when accepting/declining
-reservation buttons are only available when necessary
-added average rating to offers show and index
-added Bastien's stimulus controller to show rating
=> minor fixes

app/assets/stylesheets/components/_button.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/offers/index.html.erb, app/views/offers/show.html.erb, app/views/profiles/profile.html.erb, app/views/reservations/_form.html.erb, app/views/reservations/_reservation.html.erb, app/views/reviews/_form.html.erb
Applied class button-normal-a on link_to directly and added class button-link for sign-up sign-in
=> Buttons ok for now -pls

app/views/profiles/profile.html.erb
=> Corrected no reviews yet if no reviews

app/assets/stylesheets/components/_card.scss, app/views/offers/show.html.erb, app/views/reservations/edit.html.erb
=> Changed few things on buttons

app/views/reservations/index.html.erb, app/views/reservations/show.html.erb
=> Reservations responsive
